In [8]:
#Arthematic Functions
import numpy as np
#Shuffle
var=np.array([1,2,3,4,5,6])
np.random.shuffle(var)
print(var)

print ()
# Unique
print("unique")
var1=np.array([1,2,3,4,2,5,4,6,5,6])
np.unique(var1)
print(var1)
var2=np.array([1,2,3,4,2,5,4,6,5,6])
x1=np.unique(var2,return_index=True,return_counts=True)
print(x1)
print ()

#Resize
print("Resize")
var3=np.array([1,2,3,4,2,5,4,6,5,6])
x2=np.resize(var3,(2,3))
print(x2)




[3 2 6 5 4 1]

unique
[1 2 3 4 2 5 4 6 5 6]
(array([1, 2, 3, 4, 5, 6]), array([0, 1, 2, 3, 5, 7]), array([1, 2, 1, 2, 2, 2]))

Resize
[[1 2 3]
 [4 2 5]]


In [ ]:
#flatlen & reval  ->  2D & 3D array ko  1D ma convert karna 
# order{"c","f","a","k"}
var3=np.array([[1,2,3,4,2],[5,4,6,5,6]])
print(np.ravel(var3,order="c"))  # original view karta ha 
print(var3.flatten(order="f"))  # copy banata ha ha 


[1 2 3 4 2 5 4 6 5 6]
[1 5 2 4 3 6 4 5 2 6]


In [31]:
#Insert 1 Dimentional
#  (arrayname , position , value)
var =np.array ([1,2,3,4])
print(var)
v=np.insert(var,(2,4),6)
print(v)

#2 Dimentioanl 
var1 =np.array ([[1,2,3,4],[6,7,8,9]])
print(var1)
k=np.insert(var1,1,(5) ,axis=0)  # coloumn insert
M=np.insert(var1,3,(5,10) ,axis=1)  #  row insert
print(k)
print(M)


[1 2 3 4]
[1 2 6 3 4 6]
[[1 2 3 4]
 [6 7 8 9]]
[[1 2 3 4]
 [5 5 5 5]
 [6 7 8 9]]
[[ 1  2  3  5  4]
 [ 6  7  8 10  9]]


In [ ]:
# Append Function  add value at last
#  1 Dimention
var =np.array ([1,2,3,4])

x=np.append(var,6.5)
print (x)
#  2 Dimention
var1 =np.array ([[1,2,3,4],[6,7,8,9]])
x1= np.append(var1,77)
print(x1)



[1.  2.  3.  4.  6.5]
[ 1  2  3  4  6  7  8  9 77]


In [36]:
#  Delete    1 Dimention
var =np.array ([1,2,3,4])
d= np.delete (var,2)
print (d)


[1 2 4]
